### PR TITLE
Add ownership.rs koan file

### PR DESCRIPTION
**Pull request by corincerami**

### CODE REVIEW

**Comment by corincerami** [comment]
Still want to add some examples about explicit and implicit lifetime stuff.

**Comment by corincerami** [comment]
@crazymykl Any changed needed?

**Comment by crazymykl** [comment]
Is it intentional that many of these lack blanks?

**Comment by corincerami** [comment]
Yes. If you attempt the koans you'll see that a lot of them need something changed, added, or removed rather than just filling in a blank.

**Pull request merged**
